# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 784489e7222cf8272bc506d05d7408aa95e2e790cc2e401a99def71c0c790396bf2786c10e6a6980c6fdd3e06e2ff33dbc0a45a559ef3c545c7e6ed5e2fd1129

test:
  secret_key_base: 27d7f0d2f8115fb27e0a6a68996d8875b5dbfb60f89c1458580f33935306d3fc98c096b53d3b981fceaf66ed4545c01036e1dbbf090cf811d573d124e85fda66

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
